### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/expense-tracker#1]
Users need to be able to group expenses, and to invite other users to track expenses.

The group will be the core of how the app works: a user signs up and creates her first group, then invites others to join that group. They create categories (with splits) attached to the group, and then attach expenses to those categories.
## Todo
- [x] Define the group model
- [x] Create the group store
- [x] Tie categories to groups
- [x] Tie users to groups
- [ ] Make sure the app can only access data for the logged in user's groups (moved to its own issue in #10)
### Proposed Group Model

This should be something simple:

``` js
type Group = Map({
  id: string,
  ownerID: string, // personID who created the group (is this necessary, actually?)
  members: Object<string>, // personID for each group member
});
```

Categories and expenses need to be included in the groups as well — maybe add a `groupID` tag? Names are already not required to be unique, so this could be a pretty simple fix. Expenses are already grouped by category, so only categories need a group ID. I think. Keep this as simple as possible.

After this is implemented, the API should only be able to return data for groups the logged in user belongs to.

**Comment by jlengstorf** [comment]
Groups should have a name.

``` js
type Group = Map({
  id: string,
  name: string,
  ownerID: string, // personID who created the group (is this necessary, actually?)
  members: Array<string>, // personID for each group member
});
```
