### ISSUE TITLE
Create OAuth-dependent data flow

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/expense-tracker#10]
Flow should be:
## Part 1: Login and Loading User + Groups
- [x] User logs in (hello.js)
- [x] App retrieves (or creates) a user based on OAuth email
- [x] AppState is updated with logged in user data
- [x] Successful store of user data dispatches a "get user groups" action
- [x] App loads all groups for the given user from GroupStore
- [ ] AppState is updated with group data
- [ ] App renders components to show available groups to the user
## Part 2: Group Selection and Loading Categories + Expenses
- [ ] User selects the group to display
- [ ] App dispatches "view group" action
- [ ] AppState is updated with currently viewed group ID
- [ ] Successful store of group data dispatches a "get user categories" action
- [ ] App loads all categories with the appropriate group ID
- [ ] AppState is updated with category data
- [ ] Successful store of category data dispatches "get expenses" action
- [ ] App loads all expenses matching category ID(s)
- [ ] AppState is updated with expense data
- [ ] Successful store of expense data dispatches "get debts" action
- [ ] App initializes the SpendingStore and DebtStore
- [ ] AppState is updated with spending and debt data
- [ ] Successful store of spending and debt data dispatches "app ready" action
- [ ] App renders components to show expenses and add expense form to the user
