### ISSUE TITLE
Create app routing

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/expense-tracker#3]
The app isn't going to handle the non-logged in part of the site. That should probably be a static page of some sort.

The app will need the following views:
- [x] Login (`/login`) — view creation tracked in #4 
- [x] Home Screen (`/home`) — view creation tracked in #5 
- [x] Account Details (`/account`) — view creation tracked in #7 
- [x] View Expenses (`/:group_id/expenses`)
- [x] Categories/Splits (`/:group_id/categories`) — view creation tracked in #8 
- [x] Group Settings (`/:group_id/settings`) — view creation tracked in #9

Probably use `react-router` for this, but look into other options as well. The History API is probably the right move, too.

**Comment by jlengstorf** [comment]
The basics of routing are in place, so _technically_ this is done. Leaving it open until all the logic for routing is in place to match the specified routes above.
